pipeline {
    agent any

    environment {
        CLASSPATH = "lib/junit-jupiter-api-5.7.1.jar:lib/junit-platform-console-standalone-1.7.1.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
                sh 'mkdir -p classes'
                sh 'javac -encoding UTF-8 -d classes -cp $CLASSPATH Mission2/src/*.java'
            }
        }
        stage('Test') {
            steps {
                // JUnit 5 테스트 실행
                sh 'java -cp $CLASSPATH:classes org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
            }
        }
    }
    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
