pipeline {
    agent any

    environment {
        JAVA_OPTS = '-Dfile.encoding=UTF-8'
    }

    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    // Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
                    def junitClasspath = 'eclipse/plugins/junit-jupiter-api-5.7.1.jar:eclipse/plugins/junit-platform-console-standalone-1.7.1.jar'
                    sh 'mkdir -p classes'
                    sh "javac -encoding UTF-8 -cp ${junitClasspath} -d classes Mission2/src/*.java"
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // JUnit 5 테스트 실행
                    def junitClasspath = 'classes:eclipse/plugins/junit-jupiter-api-5.7.1.jar:eclipse/plugins/junit-platform-console-standalone-1.7.1.jar'
                    sh "java -Dfile.encoding=UTF-8 -cp ${junitClasspath} org.junit.platform.console.ConsoleLauncher --scan-classpath --classpath classes | tee test_results.txt"
                }
            }
        }
    }
    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
